CREATE TABLE [dbo].[PersonsHistory]
(
	[PersonHistoryId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWSEQUENTIALID()),
	[PersonId] UNIQUEIDENTIFIER NOT NULL,
	[FirstName] NVARCHAR(512) NOT NULL,
	[MiddleName] NVARCHAR(512) NULL,
	[Surname] NVARCHAR(512) NOT NULL,
	[DateOfBirth] DATE NOT NULL,
	[TimestampCreated] DATETIME NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT FK_PersonsHistory_Persons FOREIGN KEY(PersonId) REFERENCES dbo.Persons(PersonId)
)